name: Identity Verification Action

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch: # This allows you to run it manually

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 25ds2000022@ds.study.iitm.ac.in
        run: echo "Action triggered for student verification."
